/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarHistory;

/**
 *
 * @author Dell
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarHistory history;
    public ViewJPanel(CarHistory history) {
        initComponents();
        this.history=history;
        populateTable();
        currentDate();
    }

    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        txtLastUpdated.setText((month+1)+"/"+day+"/"+year+ " " + hour+":"+(minute)+":"+second+" Hrs" );
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewCars = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewCars = new javax.swing.JTable();
        lblBrand = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        lblModelNo = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        lblMfgYear = new javax.swing.JLabel();
        txtMfgYr = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        lblMaintCertiDate = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblAvailibility = new javax.swing.JLabel();
        txtSeatNum = new javax.swing.JTextField();
        txtMaintCerti = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        lblViewSerialNo = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        lblLastUpdated = new javax.swing.JLabel();
        txtLastUpdated = new javax.swing.JTextField();

        lblViewCars.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewCars.setText("View Cars");

        tblViewCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Brand", "Model No. ", "Manufacturing Year", "No. of Seats", "City", "Maintenance", "Availability"
            }
        ));
        tblViewCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewCarsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblViewCars);

        lblBrand.setText("Brand Name:");

        lblModelNo.setText("Model No:");

        lblMfgYear.setText("Manufacturing Year:");

        lblSeats.setText("No. of Seats:");

        lblMaintCertiDate.setText("    Maintenance Certificate Date:");

        lblCity.setText("  City:");

        lblAvailibility.setText("Availability:");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblViewSerialNo.setText("Serial No.");

        txtSerialNum.setEditable(false);

        lblLastUpdated.setText("Last Updated Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(lblViewCars)
                        .addGap(105, 105, 105)
                        .addComponent(lblLastUpdated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLastUpdated))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblModelNo)
                    .addComponent(lblBrand)
                    .addComponent(lblAvailibility)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeats)
                    .addComponent(lblMaintCertiDate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMfgYear)
                    .addComponent(lblViewSerialNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtModelNum, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtSeatNum, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtMaintCerti, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtMfgYr, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtSerialNum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewCars)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLastUpdated)
                        .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMfgYear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMfgYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeatNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintCertiDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaintCerti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailibility)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblViewCars.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblViewCars.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex,0);
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be updated.");
            return;
        }
        
        else{
           /* model.setValueAt(txtBrandName.getText(), selectedRowIndex, 1);
            model.setValueAt(txtCity.getText(), selectedRowIndex, 2);
            model.setValueAt(txtMaintCerti.getText(), selectedRowIndex, 3);
            model.setValueAt(txtMfgYr.getText(), selectedRowIndex, 4);
            model.setValueAt(txtModelNum.getText(), selectedRowIndex, 5);
            model.setValueAt(txtSeatNum.getText(), selectedRowIndex, 6);
            model.setValueAt(txtAvailability.getText(), selectedRowIndex, 7);
*/      
        int serialNo = Integer.parseInt(txtSerialNum.getText());
        String brand = txtBrandName.getText();
        String modelNo = txtModelNum.getText();
        String manufacturing_date = txtMfgYr.getText();
        int noOfSeats = Integer.parseInt(txtSeatNum.getText());
        String city = txtCity.getText();
        String maintCertiExiryDate = txtMaintCerti.getText();
        //String selectedValue = jAvailableBox.getSelectedItem().toString();
       //Car c = history.addNewCars();
       Car c = history.getCarbySerialNo(serialNo-1);
       
       c.setSerialNo(serialNo);
       c.setBrand(brand);
       c.setModelNo(modelNo);
       c.setManufacturing_date(LocalDate.parse(manufacturing_date));
       c.setNumOfSeats(noOfSeats);
       c.setCity(city); 
       c.setMaintCertiExpiryDate(LocalDate.parse(maintCertiExiryDate));
       //c.setAvailability(selectedValue);
      
        }
        
         // JOptionPane.showMessageDialog(this, "Selected car details updated.");
        
        populateTable();
        
         //Reset text fields to empty when Save button is clicked
        txtSerialNum.setText("");
        txtBrandName.setText("");
        txtModelNum.setText("");
        txtMaintCerti.setText("");
        txtMfgYr.setText("");
        txtSeatNum.setText("");
        txtCity.setText("");
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblViewCars.getSelectedRow();
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblViewCars.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex,0);
        
        history.deleteCars(selectedCar);
        
        JOptionPane.showMessageDialog(this, "Selected car details deleted");
        
        populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblViewCars.getSelectedRow();
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblViewCars.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex,0);
        
        txtBrandName.setText(String.valueOf(selectedCar.getBrand()));
        txtModelNum.setText(String.valueOf(selectedCar.getModelNo()));
        txtMfgYr.setText(String.valueOf(selectedCar.getManufacturing_date()));
        txtCity.setText(String.valueOf(selectedCar.getCity()));
        txtSeatNum.setText(String.valueOf(selectedCar.getNumOfSeats()));
        txtMaintCerti.setText(String.valueOf(selectedCar.getMaintCertiExpiryDate()));
        //txtAvailability.setText(String.valueOf(Car.getAvailability()));
        txtSerialNum.setText(String.valueOf(selectedCar.getSerialNo()));
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void tblViewCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewCarsMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblViewCars.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblViewCars.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex,0);
        
        txtBrandName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtModelNum.setText(model.getValueAt(selectedRowIndex,  2).toString());
        txtMfgYr.setText(model.getValueAt(selectedRowIndex, 3).toString());
        txtSeatNum.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txtMaintCerti.setText(model.getValueAt(selectedRowIndex, 6).toString());
        txtCity.setText(model.getValueAt(selectedRowIndex, 5).toString());
        txtSerialNum.setText(String.valueOf(selectedCar.getSerialNo()));
        
        
        
    }//GEN-LAST:event_tblViewCarsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvailibility;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblMaintCertiDate;
    private javax.swing.JLabel lblMfgYear;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblViewCars;
    private javax.swing.JLabel lblViewSerialNo;
    private javax.swing.JTable tblViewCars;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtMaintCerti;
    private javax.swing.JTextField txtMfgYr;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSeatNum;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblViewCars.getModel();
        model.setRowCount(0);
        
        for(Car c : history.getCarList()){
            
            Object[] row = new Object[9];
            row[0] = c;
            row[1] = c.getBrand();
            row[2] = c.getModelNo();
            row[3] = c.getManufacturing_date();
            row[4] = c.getNumOfSeats();
            row[5] = c.getCity();
            row[6] = c.getMaintCertiExpiryDate();
            row[7] = c.getAvailability();
            row[8] = "";
            
            model.addRow(row);
                    
        }
    }
    
}
